# Generated by Django 3.0.5 on 2020-05-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='random',
            name='user',
        ),
    ]
