# Generated by Django 3.0.8 on 2021-05-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210428_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='files',
            field=models.CharField(max_length=200),
        ),
    ]
