# Generated by Django 3.0.5 on 2020-05-15 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200515_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2020, 5, 15, 17, 13, 23, 876833)),
        ),
    ]
