# Generated by Django 3.0.5 on 2020-05-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20200515_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, upload_to='postimages/'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
