# Generated by Django 3.0.5 on 2020-05-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20200515_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(default='', max_length=250),
        ),
    ]
