# Generated by Django 3.0.5 on 2020-05-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_remove_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, upload_to='postimages/'),
        ),
    ]
